name: Translation Evaluation

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  translation-eval:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Debug environment
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        echo "Checking environment variables..."
        if ($env:OPENAI_API_KEY) {
          echo "OPENAI_API_KEY is set (length: $($env:OPENAI_API_KEY.Length))"
        } else {
          echo "OPENAI_API_KEY is NOT set"
        }

    - name: Run unit tests
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        pytest tests -v --tb=short --strict-markers -m "not translation_eval"

    - name: Run translation evaluation
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        python src/evaluate_translation.py

    - name: Run pytest with translation eval marker
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        pytest tests -m translation_eval -v --tb=short

    - name: Upload evaluation results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: translation-evaluation-results
        path: |
          *.log
          evaluation_results.json
          .pytest_cache/
          test-results.xml
          htmlcov/
